### ISSUE TITLE
hide tracked for npm ignore

### ISSUE THREAD

**Issue by VolodymyrPliuta** [MichaelDimmitt/my-bashrc-git-overrides#1]

**Comment by MichaelDimmitt** [comment]
hide tracked for npm ignore
for people who publish npm packages

**Comment by MichaelDimmitt** [comment]
Need to test to see if this is needed.

What happens if I have already published previous packages with files included like the src directory.
If I add 'src' to the npm_ignore it should hide those files in future publications.

It should not care about previous publications.
If that is the case than there is no tracking occuring and this project would not be needed for that use case.

**Comment by MichaelDimmitt** [comment]
@VolodymyrPliuta , you put this on the wrong repo ...

**Comment by VolodymyrPliuta** [comment]
> hide tracked for npm ignore
> for people who publish npm packages

@MichaelDimmitt  .npmignore is not just for people who publish npm packages it can be used the same as .gitignore plus if you publish your package to npm it will ignore what is inside of .npmignore

I see I re-opened it in wrong repo. Oops... 
![image](https://user-images.githubusercontent.com/18120588/109900583-9f3c4380-7c65-11eb-8eb9-4971d018881b.png)
my bad 

I can't move it to different repo now, but you can delete it as you DELETED this issue when I opened it initially with a description of an issue and steps that need to be done to solve it
